// Blood on the Clocktower characters data with enhanced metadata
export const getDefaultCharacters = () => [
  // 村民
  {
    id: 'chef',
    name: '厨师',
    name_en: 'Chef',
    team: 'townsfolk',
    ability: '你能得知有多少对邪恶玩家彼此相邻而坐。',
    firstNight: 39,
    otherNight: 0,
    edition: 'tb',
    complexity: 'simple',
    tags: ['information', 'setup']
  },
  {
    id: 'empath',
    name: '共情者',
    name_en: 'Empath',
    team: 'townsfolk',
    ability: '每个夜晚，你能得知与你相邻的两名存活玩家中有多少名邪恶玩家。',
    firstNight: 50,
    otherNight: 69,
    edition: 'tb',
    complexity: 'simple',
    tags: ['information', 'detection']
  },
  {
    id: 'fortune_teller',
    name: '占卜师',
    name_en: 'Fortune Teller',
    team: 'townsfolk',
    ability: '每个夜晚，选择两名玩家：你能得知他们其中是否有恶魔。会有一名善良玩家始终被你的能力误判为恶魔。',
    firstNight: 51,
    otherNight: 70,
    edition: 'tb',
    complexity: 'medium',
    tags: ['information', 'detection', 'false-positive']
  },
  {
    id: 'investigator',
    name: '调查员',
    name_en: 'Investigator',
    team: 'townsfolk',
    ability: '你能得知有多少名爪牙在你的两名邻座玩家之间（按顺时针方向）。',
    firstNight: 52,
    otherNight: 0,
    edition: 'tb',
    complexity: 'simple',
    tags: ['information', 'setup']
  },
  {
    id: 'librarian',
    name: '图书管理员',
    name_en: 'Librarian',
    team: 'townsfolk',
    ability: '你能得知两名玩家中的一名是哪个外来者，或得知没有外来者在场。',
    firstNight: 53,
    otherNight: 0,
    edition: 'tb',
    complexity: 'simple',
    tags: ['information', 'setup']
  },
  {
    id: 'mayor',
    name: '市长',
    name_en: 'Mayor',
    team: 'townsfolk',
    ability: '如果只有三名存活玩家且今天没有处决，你的阵营获胜。如果你死于处决，另一名玩家可能会立即被处决。',
    firstNight: 0,
    otherNight: 0,
    edition: 'tb',
    complexity: 'medium',
    tags: ['win-condition', 'execution']
  },
  {
    id: 'monk',
    name: '僧侣',
    name_en: 'Monk',
    team: 'townsfolk',
    ability: '每个夜晚*，选择除你以外的一名玩家：恶魔今晚不能选择该玩家。',
    firstNight: 28,
    otherNight: 37,
    edition: 'tb',
    complexity: 'simple',
    tags: ['protection', 'active']
  },
  {
    id: 'ravenkeeper',
    name: '渡鸦管理员',
    name_en: 'Ravenkeeper',
    team: 'townsfolk',
    ability: '如果你死于恶魔的袭击，你能得知一名玩家的角色。',
    firstNight: 0,
    otherNight: 47,
    edition: 'tb',
    complexity: 'simple',
    tags: ['information', 'death-trigger']
  },
  {
    id: 'slayer',
    name: '猎手',
    name_en: 'Slayer',
    team: 'townsfolk',
    ability: '每局游戏限一次，在白天时，公开选择一名玩家：如果该玩家是恶魔，该玩家死亡。',
    firstNight: 0,
    otherNight: 0,
    edition: 'tb',
    complexity: 'simple',
    tags: ['killing', 'one-time', 'day-action']
  },
  {
    id: 'soldier',
    name: '士兵',
    name_en: 'Soldier',
    team: 'townsfolk',
    ability: '你不会死于恶魔的能力。',
    firstNight: 0,
    otherNight: 0,
    edition: 'tb',
    complexity: 'simple',
    tags: ['protection', 'passive']
  },
  {
    id: 'undertaker',
    name: '殡仪员',
    name_en: 'Undertaker',
    team: 'townsfolk',
    ability: '每个夜晚*（首个夜晚除外），你能得知前一天白天死于处决的玩家的角色。',
    firstNight: 0,
    otherNight: 78,
    edition: 'tb',
    complexity: 'simple',
    tags: ['information', 'execution']
  },
  {
    id: 'virgin',
    name: '处女',
    name_en: 'Virgin',
    team: 'townsfolk',
    ability: '你第一次被提名时，如果提名你的玩家是村民，该玩家被处决。',
    firstNight: 0,
    otherNight: 0,
    edition: 'tb',
    complexity: 'medium',
    tags: ['protection', 'nomination', 'execution']
  },
  {
    id: 'washerwoman',
    name: '洗衣妇',
    name_en: 'Washerwoman',
    team: 'townsfolk',
    ability: '你能得知两名玩家中的一名是哪个村民，或得知他们都不是村民。',
    firstNight: 56,
    otherNight: 0,
    edition: 'tb',
    complexity: 'simple',
    tags: ['information', 'setup']
  },
  // 外来者
  {
    id: 'butler',
    name: '管家',
    name_en: 'Butler',
    team: 'outsider',
    ability: '每个夜晚，选择一名玩家（不能是你自己）：明天你只能投票给该玩家。',
    firstNight: 40,
    otherNight: 60,
    edition: 'tb',
    complexity: 'medium',
    tags: ['voting', 'restriction']
  },
  {
    id: 'drunk',
    name: '酒鬼',
    name_en: 'Drunk',
    team: 'outsider',
    ability: '你以为你是一个村民角色，但实际上不是。你不知道你是酒鬼。',
    firstNight: 0,
    otherNight: 0,
    edition: 'tb',
    complexity: 'complex',
    tags: ['madness', 'hidden']
  },
  {
    id: 'recluse',
    name: '隐士',
    name_en: 'Recluse',
    team: 'outsider',
    ability: '你可能被善良玩家的能力误判为邪恶，或被视为爪牙或恶魔。',
    firstNight: 0,
    otherNight: 0,
    edition: 'tb',
    complexity: 'medium',
    tags: ['false-positive', 'detection']
  },
  {
    id: 'saint',
    name: '圣者',
    name_en: 'Saint',
    team: 'outsider',
    ability: '如果你死于处决，你的阵营失败。',
    firstNight: 0,
    otherNight: 0,
    edition: 'tb',
    complexity: 'simple',
    tags: ['win-condition', 'execution']
  },
  // 爪牙
  {
    id: 'baron',
    name: '男爵',
    name_en: 'Baron',
    team: 'minion',
    ability: '会有额外的外来者在场。[+2外来者]',
    setup: true,
    firstNight: 0,
    otherNight: 0,
    edition: 'tb',
    complexity: 'simple',
    tags: ['setup', 'modifier']
  },
  {
    id: 'poisoner',
    name: '投毒者',
    name_en: 'Poisoner',
    team: 'minion',
    ability: '每个夜晚，选择一名玩家：该玩家中毒直到下个黄昏。',
    firstNight: 19,
    otherNight: 8,
    edition: 'tb',
    complexity: 'medium',
    tags: ['poisoning', 'debuff']
  },
  {
    id: 'scarlet_woman',
    name: '红唇女郎',
    name_en: 'Scarlet Woman',
    team: 'minion',
    ability: '如果恶魔死亡时有5名及以上的存活玩家，你变成该恶魔。',
    firstNight: 0,
    otherNight: 22,
    edition: 'tb',
    complexity: 'medium',
    tags: ['transformation', 'backup']
  },
  {
    id: 'spy',
    name: '间谍',
    name_en: 'Spy',
    team: 'minion',
    ability: '每个夜晚，你能得知魔典。你可能被善良玩家的能力误判为善良，或被视为村民或外来者。',
    firstNight: 58,
    otherNight: 77,
    edition: 'tb',
    complexity: 'complex',
    tags: ['information', 'false-positive', 'grimoire']
  },
  // 恶魔
  {
    id: 'imp',
    name: '小恶魔',
    name_en: 'Imp',
    team: 'demon',
    ability: '每个夜晚*，选择一名玩家：该玩家死亡。如果你自杀，一名爪牙变成小恶魔。',
    firstNight: 24,
    otherNight: 32,
    edition: 'tb',
    complexity: 'medium',
    tags: ['killing', 'transformation']
  }
];